/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Artist

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artist 
 * @param tracks 
 */
@Serializable
data class ArtistsArtistIdTrackIdsByRatingGet200Response (

    @SerialName(value = "artist") val artist: Artist? = null,

    @SerialName(value = "tracks") val tracks: kotlin.collections.List<kotlin.String>? = null

)

