/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BestResult

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * лучший результат поиска
 *
 * @param type Тип лучшего результата
 * @param text 
 * @param result 
 */
@Serializable
data class Best (

    /* Тип лучшего результата */
    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "text") val text: kotlin.String? = null,

    @SerialName(value = "result") val result: BestResult? = null

)

