/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * часть текста с ссылкой на лицензионное соглашение
 *
 * @param text Часть текста.
 * @param url Ссылка на лицензионное соглашение.
 */
@Serializable
data class LicenceTextPart (

    /* Часть текста. */
    @SerialName(value = "text") val text: kotlin.String? = null,

    /* Ссылка на лицензионное соглашение. */
    @SerialName(value = "url") val url: kotlin.String? = null

)

