/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Cover
import org.openapitools.client.models.Owner
import org.openapitools.client.models.PlaylistTagsInner
import org.openapitools.client.models.TrackItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * play list data
 *
 * @param playlistUuid 
 * @param description 
 * @param descriptionFormatted 
 * @param available 
 * @param collective 
 * @param cover 
 * @param created 
 * @param modified 
 * @param backgroundColor 
 * @param textColor 
 * @param durationMs 
 * @param isBunner 
 * @param isPremiere 
 * @param kind 
 * @param ogImage 
 * @param owner 
 * @param prerolls 
 * @param revision 
 * @param snapshot 
 * @param tags 
 * @param title 
 * @param trackCount 
 * @param uid 
 * @param visibility 
 * @param likesCount 
 * @param tracks 
 */
@Serializable
data class Playlist (

    @SerialName(value = "playlistUuid") val playlistUuid: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "descriptionFormatted") val descriptionFormatted: kotlin.String? = null,

    @SerialName(value = "available") val available: kotlin.Boolean? = null,

    @SerialName(value = "collective") val collective: kotlin.Boolean? = null,

    @SerialName(value = "cover") val cover: Cover? = null,

    @SerialName(value = "created") val created: kotlin.String? = null,

    @SerialName(value = "modified") val modified: kotlin.String? = null,

    @SerialName(value = "backgroundColor") val backgroundColor: kotlin.String? = null,

    @SerialName(value = "textColor") val textColor: kotlin.String? = null,

    @SerialName(value = "durationMs") val durationMs: kotlin.Double? = null,

    @SerialName(value = "isBunner") val isBunner: kotlin.Boolean? = null,

    @SerialName(value = "isPremiere") val isPremiere: kotlin.Boolean? = null,

    @SerialName(value = "kind") val kind: kotlin.Double? = null,

    @SerialName(value = "ogImage") val ogImage: kotlin.String? = null,

    @SerialName(value = "owner") val owner: Owner? = null,

    @SerialName(value = "prerolls") val prerolls: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "revision") val revision: kotlin.Double? = null,

    @SerialName(value = "snapshot") val snapshot: kotlin.Double? = null,

    @SerialName(value = "tags") val tags: kotlin.collections.List<PlaylistTagsInner>? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "trackCount") val trackCount: kotlin.Double? = null,

    @SerialName(value = "uid") val uid: kotlin.Double? = null,

    @SerialName(value = "visibility") val visibility: Playlist.Visibility? = null,

    @SerialName(value = "likesCount") val likesCount: kotlin.Double? = null,

    @SerialName(value = "tracks") val tracks: kotlin.collections.List<TrackItem>? = null

) {

    /**
     * 
     *
     * Values: `public`,`private`
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "public") `public`("public"),
        @SerialName(value = "private") `private`("private");
    }
}

