/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Status

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * статус активации промо-кода
 *
 * @param status Статус операции
 * @param statusDesc Описание статуса
 * @param accountStatus 
 */
@Serializable
data class PromoCodeStatus (

    /* Статус операции */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* Описание статуса */
    @SerialName(value = "statusDesc") val statusDesc: kotlin.String? = null,

    @SerialName(value = "accountStatus") val accountStatus: Status? = null

)

