/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountPassportPhonesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Основная информация об аккаунте
 *
 * @param now Текущая дата и время
 * @param uid Уникальный идентификатор
 * @param login Виртуальное имя (обычно e-mail)
 * @param region Регион
 * @param fullName Полное имя (имя и фамилия)
 * @param secondName Фамилия
 * @param firstName Имя
 * @param displayName Отображаемое имя
 * @param serviceAvailable Доступен ли сервис
 * @param hostedUser Является ли пользователем чьим-то другим
 * @param passportPhones Мобильные номера
 */
@Serializable
data class Account (

    /* Текущая дата и время */
    @SerialName(value = "now") val now: kotlin.String? = null,

    /* Уникальный идентификатор */
    @SerialName(value = "uid") val uid: kotlin.Double? = null,

    /* Виртуальное имя (обычно e-mail) */
    @SerialName(value = "login") val login: kotlin.String? = null,

    /* Регион */
    @SerialName(value = "region") val region: kotlin.Double? = null,

    /* Полное имя (имя и фамилия) */
    @SerialName(value = "fullName") val fullName: kotlin.String? = null,

    /* Фамилия */
    @SerialName(value = "secondName") val secondName: kotlin.String? = null,

    /* Имя */
    @SerialName(value = "firstName") val firstName: kotlin.String? = null,

    /* Отображаемое имя */
    @SerialName(value = "displayName") val displayName: kotlin.String? = null,

    /* Доступен ли сервис */
    @SerialName(value = "serviceAvailable") val serviceAvailable: kotlin.Boolean? = null,

    /* Является ли пользователем чьим-то другим */
    @SerialName(value = "hostedUser") val hostedUser: kotlin.Boolean? = null,

    /* Мобильные номера */
    @SerialName(value = "passport-phones") val passportPhones: kotlin.collections.List<AccountPassportPhonesInner>? = null

)

