/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models

import api.models.InvocationInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param invocationInfo 
 * @param result режимы экспериментальных функций
 */
@Serializable
data class AccountExperimentsGet200Response (

    @SerialName(value = "invocationInfo") val invocationInfo: InvocationInfo? = null,

    /* режимы экспериментальных функций */
    @SerialName(value = "result") val result: kotlin.String? = null

)

