/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models

import api.models.Track

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * рекомендации для плейлиста
 *
 * @param batchId Уникальный идентификатор партии треков
 * @param tracks 
 */
@Serializable
data class PlaylistRecommendations (

    /* Уникальный идентификатор партии треков */
    @SerialName(value = "batch_id") val batchId: kotlin.String? = null,

    @SerialName(value = "tracks") val tracks: kotlin.collections.List<Track>? = null

)

