/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param uid Уникальный идентификатор пользователя владеющим плейлистом
 * @param kind Уникальный идентификатор плейлиста
 */
@Serializable
data class PlaylistId (

    /* Уникальный идентификатор пользователя владеющим плейлистом */
    @SerialName(value = "uid") val uid: Long,

    /* Уникальный идентификатор плейлиста */
    @SerialName(value = "kind") val kind: Long

)

