/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * цена
 *
 * @param amount Количество единиц
 * @param currency Валюта
 */
@Serializable
data class Price (

    /* Количество единиц */
    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    /* Валюта */
    @SerialName(value = "currency") val currency: kotlin.String? = null

)

