/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models

import api.models.LicenceTextPart
import api.models.Price

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * продаваемый продукт
 *
 * @param productId Уникальный идентификатор.
 * @param type Тип продаваемого.
 * @param commonPeriodDuration Длительность общего периода.
 * @param duration Длительность.
 * @param trialDuration Длительность испытательного срока.
 * @param price 
 * @param feature Предоставляемая возможность.
 * @param debug Отладочный продукт.
 * @param plus Даёт ли подписку \"Плюс\".
 * @param cheapest Самый дешёвый (лучшее предложение).
 * @param title Заголовок продукта.
 * @param familySub Семейная ли подписка.
 * @param fbImage Картинка для превью на facebook.
 * @param fbName Заголовок превью на facebook.
 * @param family Доступно ли для семьи.
 * @param features Список предоставляемых возможностей.
 * @param description Описание.
 * @param available Доступна ли покупка.
 * @param trialAvailable Доступен ли пробный период.
 * @param trialPeriodDuration Длительность пробного периода.
 * @param introPeriodDuration Длительность вступительного периода TODO.
 * @param introPrice 
 * @param startPeriodDuration Длительность первого срока (за меньшую цену).
 * @param startPrice 
 * @param licenceTextParts 
 * @param vendorTrialAvailable Доступен испытательный срок продавца TODO.
 * @param buttonText Текст кнопки.
 * @param buttonAdditionalText Дополнительный текст кнопки.
 * @param paymentMethodTypes Способы оплаты.
 */
@Serializable
data class Product (

    /* Уникальный идентификатор. */
    @SerialName(value = "productId") val productId: kotlin.String? = null,

    /* Тип продаваемого. */
    @SerialName(value = "type") val type: kotlin.String? = null,

    /* Длительность общего периода. */
    @SerialName(value = "commonPeriodDuration") val commonPeriodDuration: kotlin.String? = null,

    /* Длительность. */
    @SerialName(value = "duration") val duration: kotlin.Double? = null,

    /* Длительность испытательного срока. */
    @SerialName(value = "trialDuration") val trialDuration: kotlin.Double? = null,

    @SerialName(value = "price") val price: Price? = null,

    /* Предоставляемая возможность. */
    @SerialName(value = "feature") val feature: kotlin.String? = null,

    /* Отладочный продукт. */
    @SerialName(value = "debug") val debug: kotlin.Boolean? = null,

    /* Даёт ли подписку \"Плюс\". */
    @SerialName(value = "plus") val plus: kotlin.Boolean? = null,

    /* Самый дешёвый (лучшее предложение). */
    @SerialName(value = "cheapest") val cheapest: kotlin.Boolean? = null,

    /* Заголовок продукта. */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* Семейная ли подписка. */
    @SerialName(value = "familySub") val familySub: kotlin.Boolean? = null,

    /* Картинка для превью на facebook. */
    @SerialName(value = "fbImage") val fbImage: kotlin.String? = null,

    /* Заголовок превью на facebook. */
    @SerialName(value = "fbName") val fbName: kotlin.String? = null,

    /* Доступно ли для семьи. */
    @SerialName(value = "family") val family: kotlin.Boolean? = null,

    /* Список предоставляемых возможностей. */
    @SerialName(value = "features") val features: kotlin.collections.List<kotlin.String>? = null,

    /* Описание. */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* Доступна ли покупка. */
    @SerialName(value = "available") val available: kotlin.Boolean? = null,

    /* Доступен ли пробный период. */
    @SerialName(value = "trialAvailable") val trialAvailable: kotlin.Boolean? = null,

    /* Длительность пробного периода. */
    @SerialName(value = "trialPeriodDuration") val trialPeriodDuration: kotlin.String? = null,

    /* Длительность вступительного периода TODO. */
    @SerialName(value = "introPeriodDuration") val introPeriodDuration: kotlin.String? = null,

    @SerialName(value = "introPrice") val introPrice: Price? = null,

    /* Длительность первого срока (за меньшую цену). */
    @SerialName(value = "startPeriodDuration") val startPeriodDuration: kotlin.String? = null,

    @SerialName(value = "startPrice") val startPrice: Price? = null,

    @SerialName(value = "licenceTextParts") val licenceTextParts: LicenceTextPart? = null,

    /* Доступен испытательный срок продавца TODO. */
    @SerialName(value = "vendorTrialAvailable") val vendorTrialAvailable: kotlin.Boolean? = null,

    /* Текст кнопки. */
    @SerialName(value = "buttonText") val buttonText: kotlin.String? = null,

    /* Дополнительный текст кнопки. */
    @SerialName(value = "buttonAdditionalText") val buttonAdditionalText: kotlin.String? = null,

    /* Способы оплаты. */
    @SerialName(value = "paymentMethodTypes") val paymentMethodTypes: kotlin.collections.List<kotlin.String>? = null

)

