/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: artist,album,track,podcast,all
 */
@Serializable
enum class SearchType {

    @SerialName(value = "artist")
    ARTIST,

    @SerialName(value = "album")
    ALBUM,

    @SerialName(value = "track")
    TRACK,

    @SerialName(value = "playlist")
    PLAYLIST,

    @SerialName(value = "podcast")
    PODCAST,

    @SerialName(value = "podcast_episode")
    PODCAST_EPISODE,

    @SerialName(value = "all")
    ALL;
}

