/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Best
import org.openapitools.client.models.SearchResult
import org.openapitools.client.models.SearchType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Результаты поиска
 *
 * @param searchResultId ID запроса
 * @param text Текст запроса
 * @param best 
 * @param albums 
 * @param artists 
 * @param playlists 
 * @param tracks 
 * @param videos 
 * @param users 
 * @param podcasts 
 * @param podcastEpisodes 
 * @param type 
 * @param page Текущая страница
 * @param perPage Результатов на странице
 * @param misspellCorrected Был ли исправлен запрос
 * @param misspellOriginal Оригинальный запрос
 * @param nocorrect Было ли отключено исправление результата
 */
@Serializable
data class Search (

    /* ID запроса */
    @SerialName(value = "searchResultId") val searchResultId: kotlin.String? = null,

    /* Текст запроса */
    @SerialName(value = "text") val text: kotlin.String? = null,

    @SerialName(value = "best") val best: Best? = null,

    @SerialName(value = "albums") val albums: SearchResult? = null,

    @SerialName(value = "artists") val artists: SearchResult? = null,

    @SerialName(value = "playlists") val playlists: SearchResult? = null,

    @SerialName(value = "tracks") val tracks: SearchResult? = null,

    @SerialName(value = "videos") val videos: SearchResult? = null,

    @SerialName(value = "users") val users: SearchResult? = null,

    @SerialName(value = "podcasts") val podcasts: SearchResult? = null,

    @SerialName(value = "podcast_episodes") val podcastEpisodes: SearchResult? = null,

    @SerialName(value = "type") val type: SearchType? = SearchType.all,

    /* Текущая страница */
    @SerialName(value = "page") val page: kotlin.Double? = null,

    /* Результатов на странице */
    @SerialName(value = "perPage") val perPage: kotlin.Double? = null,

    /* Был ли исправлен запрос */
    @SerialName(value = "misspellCorrected") val misspellCorrected: kotlin.Boolean? = null,

    /* Оригинальный запрос */
    @SerialName(value = "misspellOriginal") val misspellOriginal: kotlin.String? = null,

    /* Было ли отключено исправление результата */
    @SerialName(value = "nocorrect") val nocorrect: kotlin.Boolean? = null

)

