/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: artist,album,track,podcast,all
 */
@Serializable
enum class SearchType(val value: String) {

    @SerialName(value = "artist")
    artist("artist"),

    @SerialName(value = "album")
    album("album"),

    @SerialName(value = "track")
    track("track"),

    @SerialName(value = "playlist")
    playlist("playlist"),

    @SerialName(value = "podcast")
    podcast("podcast"),

    @SerialName(value = "podcast_episode")
    podcastEpisode("podcast_episode"),

    @SerialName(value = "all")
    all("all");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SearchType) "$data" else null

        /**
         * Returns a valid [SearchType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SearchType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

