/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Price
import org.openapitools.client.models.Product

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Предложения по покупке
 *
 * @param inAppProducts 
 * @param nativeProducts 
 * @param webPaymentUrl 
 * @param webPaymentMonthProductPrice 
 * @param promoCodesEnabled 
 */
@Serializable
data class Settings (

    @SerialName(value = "inAppProducts") val inAppProducts: kotlin.collections.List<Product>? = null,

    @SerialName(value = "nativeProducts") val nativeProducts: kotlin.collections.List<Product>? = null,

    @SerialName(value = "webPaymentUrl") val webPaymentUrl: kotlin.String? = null,

    @SerialName(value = "webPaymentMonthProductPrice") val webPaymentMonthProductPrice: Price? = null,

    @SerialName(value = "promoCodesEnabled") val promoCodesEnabled: kotlin.Boolean? = null

)

