/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models

import api.models.Account
import api.models.Alert
import api.models.Permissions
import api.models.StatusPlus
import api.models.Subscription

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param account 
 * @param permissions 
 * @param subscription 
 * @param subeditor Наличие статуса модератора проверки корректности информации
 * @param subeditorLevel Уровень статуса модератора
 * @param pretrialActive 
 * @param plus 
 * @param defaultEmail Основной e-mail адрес аккаунта
 * @param barBelow 
 */
@Serializable
data class Status (

    @SerialName(value = "account") val account: Account? = null,

    @SerialName(value = "permissions") val permissions: Permissions? = null,

    @SerialName(value = "subscription") val subscription: Subscription? = null,

    /* Наличие статуса модератора проверки корректности информации */
    @SerialName(value = "subeditor") val subeditor: kotlin.Boolean? = null,

    /* Уровень статуса модератора */
    @SerialName(value = "subeditorLevel") val subeditorLevel: kotlin.Double? = null,

    @SerialName(value = "pretrialActive") val pretrialActive: kotlin.Boolean? = null,

    @SerialName(value = "plus") val plus: StatusPlus? = null,

    /* Основной e-mail адрес аккаунта */
    @SerialName(value = "defaultEmail") val defaultEmail: kotlin.String? = null,

    @SerialName(value = "barBelow") val barBelow: Alert? = null

)

