/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * подсказки при поиске
 *
 * @param best 
 * @param suggestions 
 */
@Serializable
data class Suggestions (

    @SerialName(value = "best") val best: kotlin.String? = null,

    @SerialName(value = "suggestions") val suggestions: kotlin.collections.List<kotlin.String>? = null

)

