/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Тег
 *
 * @param id Уникальный идентификатор тега
 * @param `value` Значение тега (название в lower case)
 * @param name Название тега (отображаемое)
 * @param ogDescription Описание тега для OpenGraph
 * @param ogImage Ссылка на изображение для OpenGraph
 */
@Serializable
data class Tag (

    /* Уникальный идентификатор тега */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Значение тега (название в lower case) */
    @SerialName(value = "value") @Required val `value`: kotlin.String,

    /* Название тега (отображаемое) */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Описание тега для OpenGraph */
    @SerialName(value = "ogDescription") @Required val ogDescription: kotlin.String,

    /* Ссылка на изображение для OpenGraph */
    @SerialName(value = "ogImage") val ogImage: kotlin.String? = null

)

