/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PlaylistId
import org.openapitools.client.models.Tag

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Класс, представляющий тег и его плейлисты
 *
 * @param tag 
 * @param ids 
 */
@Serializable
data class TagResult (

    @SerialName(value = "tag") val tag: Tag? = null,

    @SerialName(value = "ids") val ids: kotlin.collections.List<PlaylistId>? = null

)

