/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models

import api.models.TrackShort

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * список треков
 *
 * @param uid Уникальный идентификатор пользователя
 * @param revisions Актуальность данных TODO
 * @param tracks Список треков в укороченной версии
 */
@Serializable
data class TracksList (

    /* Уникальный идентификатор пользователя */
    @SerialName(value = "uid") val uid: kotlin.Double? = null,

    /* Актуальность данных TODO */
    @SerialName(value = "revisions") val revisions: kotlin.Double? = null,

    /* Список треков в укороченной версии */
    @SerialName(value = "tracks") val tracks: kotlin.collections.List<TrackShort>? = null

)

