/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Укороченная версия трека с неполными данными
 *
 * @param id Уникальный идентификатор трека
 * @param albumId Уникальный идентификатор альбома
 * @param timestamp Дата
 */
@Serializable
data class TrackShort (

    /* Уникальный идентификатор трека */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* Уникальный идентификатор альбома */
    @SerialName(value = "albumId") val albumId: kotlin.String? = null,

    /* Дата */
    @SerialName(value = "timestamp") val timestamp: kotlin.String? = null

)

