/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models

import api.models.Track

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id
 * @param albumId
 * @param playCount 
 * @param recent 
 * @param timestamp 
 * @param track 
 */
@Serializable
data class TrackItem (
    val id: Long,
    val albumId: Long? = null,
    val playCount: Int? = null,
    val recent: Boolean? = null,
    val timestamp: String? = null,
    val track: Track? = null
)

