/**
 * Yandex Music Api
 *
 * Swagger документация для Yandex Music API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * видеоклипы
 *
 * @param cover URL на обложку видео.
 * @param provider Сервис поставляющий видео.
 * @param title Название видео.
 * @param providerVideoId Уникальный идентификатор видео на сервисе.
 * @param url URL на видео.
 * @param embedUrl URL на видео, находящегося на серверах Яндекса.
 * @param embed HTML тег для встраивания видео.
 */
@Serializable
data class VideoSupplement (

    /* URL на обложку видео. */
    @SerialName(value = "cover") val cover: kotlin.String? = null,

    /* Сервис поставляющий видео. */
    @SerialName(value = "provider") val provider: kotlin.String? = null,

    /* Название видео. */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* Уникальный идентификатор видео на сервисе. */
    @SerialName(value = "providerVideoId") val providerVideoId: kotlin.String? = null,

    /* URL на видео. */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* URL на видео, находящегося на серверах Яндекса. */
    @SerialName(value = "embedUrl") val embedUrl: kotlin.String? = null,

    /* HTML тег для встраивания видео. */
    @SerialName(value = "embed") val embed: kotlin.String? = null

)

